import type { Mob, Stats } from "./types";

export function createNewPlayer(): Stats {
  return {
    level: 1,
    exp: 0,
    maxHp: 100,
    hp: 100,
    strenght: 3,
    armor: 0,
    luck: 0,
    gold: 50,
  };
}

export const MOBS: Mob[] = [
  {
    id: "slime",
    name: "Slime",
    kind: "mob",
    level: 1,
    icon: "slime",
    maxHp: 28,
    mobAttack: 7,
    lootTableId: "slime",
  },
  {
    id: "rat",
    name: "Giant Rat",
    kind: "mob",
    level: 2,
    icon: "rat",
    maxHp: 36,
    mobAttack: 8,
    lootTableId: "rat",
  },
  {
    id: "bat",
    name: "Cave Bat",
    kind: "mob",
    level: 3,
    icon: "bat",
    maxHp: 44,
    mobAttack: 9,
    lootTableId: "bat",
  },
  {
    id: "spider",
    name: "Forest Spider",
    kind: "mob",
    level: 4,
    icon: "spider",
    maxHp: 52,
    mobAttack: 10,
    lootTableId: "spider",
  },
  {
    id: "wolf",
    name: "Wolf",
    kind: "mob",
    level: 5,
    icon: "wolf",
    maxHp: 62,
    mobAttack: 12,
    lootTableId: "wolf",
  },
  {
    id: "bandit",
    name: "Bandit",
    kind: "mob",
    level: 6,
    icon: "bandit",
    maxHp: 74,
    mobAttack: 13,
    lootTableId: "bandit",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    kind: "mob",
    level: 7,
    icon: "skeleton",
    maxHp: 86,
    mobAttack: 15,
    lootTableId: "skeleton",
  },
  {
    id: "ghoul",
    name: "Ghoul",
    kind: "mob",
    level: 8,
    icon: "ghoul",
    maxHp: 98,
    mobAttack: 17,
    lootTableId: "ghoul",
  },
  {
    id: "mage",
    name: "Rogue Mage",
    kind: "mob",
    level: 9,
    icon: "mage",
    maxHp: 110,
    mobAttack: 18,
    lootTableId: "mage",
  },
  {
    id: "ogre",
    name: "Ogre",
    kind: "mob",
    level: 10,
    icon: "ogre",
    maxHp: 130,
    mobAttack: 21,
    lootTableId: "ogre",
  },

  {
    id: "wraith",
    name: "Wraith",
    kind: "mob",
    level: 11,
    icon: "wraith",
    maxHp: 150,
    mobAttack: 23,
    lootTableId: "wraith",
  },
  {
    id: "knight",
    name: "Fallen Knight",
    kind: "mob",
    level: 12,
    icon: "knight",
    maxHp: 170,
    mobAttack: 25,
    lootTableId: "knight",
  },
  {
    id: "golem",
    name: "Stone Golem",
    kind: "mob",
    level: 13,
    icon: "golem",
    maxHp: 195,
    mobAttack: 27,
    lootTableId: "golem",
  },
  {
    id: "harpy",
    name: "Harpy",
    kind: "mob",
    level: 14,
    icon: "harpy",
    maxHp: 215,
    mobAttack: 29,
    lootTableId: "harpy",
  },
  {
    id: "wyrm",
    name: "Wyrm",
    kind: "mob",
    level: 15,
    icon: "wyrm",
    maxHp: 240,
    mobAttack: 32,
    lootTableId: "wyrm",
  },

  {
    id: "cultist",
    name: "Cultist",
    kind: "mob",
    level: 16,
    icon: "cultist",
    maxHp: 265,
    mobAttack: 34,
    lootTableId: "cultist",
  },
  {
    id: "assassin",
    name: "Assassin",
    kind: "mob",
    level: 17,
    icon: "assassin",
    maxHp: 295,
    mobAttack: 36,
    lootTableId: "assassin",
  },
  {
    id: "wyvern",
    name: "Wyvern",
    kind: "mob",
    level: 18,
    icon: "wyvern",
    maxHp: 330,
    mobAttack: 39,
    lootTableId: "wyvern",
  },
  {
    id: "demon",
    name: "Lesser Demon",
    kind: "mob",
    level: 19,
    icon: "demon",
    maxHp: 365,
    mobAttack: 42,
    lootTableId: "demon",
  },
  {
    id: "ancient",
    name: "Ancient Guardian",
    kind: "mob",
    level: 20,
    icon: "ancient",
    maxHp: 410,
    mobAttack: 46,
    lootTableId: "ancient",
  },
];

export const BOSSES: Mob[] = [
  {
    id: "boss_swampking",
    name: "Swamp King",
    kind: "boss",
    level: 8,
    icon: "boss1",
    maxHp: 260,
    mobAttack: 22,
    lootTableId: "boss_swampking",
  },
  {
    id: "bigspider",
    name: "Hehe spider",
    kind: "boss",
    level: 14,
    icon: "boss2",
    maxHp: 420,
    mobAttack: 33,
    lootTableId: "hehe_spider",
  },
  {
    id: "boss_voidwyrm",
    name: "Void Wyrm",
    kind: "boss",
    level: 20,
    icon: "boss3",
    maxHp: 650,
    mobAttack: 48,
    lootTableId: "boss_voidwyrm",
  },
];
